
FROM debian:bullseye

RUN apt-get update
RUN apt-get -y install git g++ cmake ninja-build pkg-config \
	libjerasure-dev nanopb libnanopb-dev libavcodec-dev libopus-dev \
	libssl-dev protobuf-compiler python3 python3-protobuf \
	libevdev-dev libudev-dev \
	libqt5opengl5-dev libqt5svg5-dev qtmultimedia5-dev libsdl2-dev

CMD []

