
FROM ubuntu:xenial

RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:beineri/opt-qt-5.12.3-xenial
RUN apt-get update
RUN apt-get -y install git g++ cmake ninja-build curl unzip python3-pip \
	libssl-dev libopus-dev qt512base qt512multimedia qt512svg \
	libgl1-mesa-dev nasm libudev-dev libva-dev fuse

CMD []

